name: graphmetric
channels:
        - conda-forge
        - pytorch
        - dglteam
        - defaults
dependencies:
        - python=3.7
        - numpy
        - pytorch=1.2
        - torchvision
        - tensorflow
        - tensorboard
        - tensorboardX
        - dgl-cuda10.0 
        - scipy
        - scikit-learn
        - joblib
        - tqdm
        - matplotlib
